version: 2
updates:
  - package-ecosystem: "composer"
    directories:
      - '/'
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
